import RecordModel from "../models/Record.js";

const createRecord = async (req, res, next) => {
  console.log(req.body);
  const {
    name,
    fatherName,
    address,
    mobile,
    imei,
    fir,
    description,
    chassNumber,
    engilneNumber,
  } = req.body;
  // errors generated by not providing required fileds have been handled at the Model layer
  try {
    const doc = new RecordModel({
      name: name,
      fatherName: fatherName,
      address: address,
      mobile: mobile,
    });
    const saved = await doc.save();
    console.log("saved ", saved);
    res.status(201).send({
      status: "success",
      message: "Record Created",
      record: saved,
    });
  } catch (error) {
    console.log(error);
    next(error); // will call the express errorHandler we implemented in
    // errorContoller and used in app.js

    //res.send({ status: "failed", message: "Unable to Register" });
  }
};
const getAllRecord = async (req, res, next) => {
  try {
    // wrapping async funtion in try..catch block incase of any asynchronouse error
    const allRecord = await RecordModel.find();
    console.log(allRecord);
    if (allRecord) {
      res.send({ status: "success", records: allRecord });
    } else res.send({ status: "failed", message: "No Record Found" });
  } catch (error) {
    console.log(error);
    next(error); //call errorHandler
  }
};
export { createRecord, getAllRecord };
